### ISSUE TITLE
compile instructions for raspberry pi

### ISSUE THREAD

**Issue by skipperearly** [Rodemfr/meteovache_pi#10]
can you please add compile instructions for the raspberry pi ? Thanks !!!

**Comment by Rodemfr** [comment]
Sorry for the late answer...
I just added compile instructions for Raspberry Pi in the _Compilation.txt_ file at root of the repository.
To test compilation, I used my own Raspberry Pi Zero. It compiled fine but since Pi Zero can not run OpenCPN, I was not able to test it  at execution. Any feedback on success or failure would be appreciated.
Ronan.

**Comment by Rodemfr** [comment]
Done
